### PR TITLE
Use container element ref in place of id

### PR DESCRIPTION
**Pull request by mortendevold**
This PR changes the container element from having an `id` attribute to using an element ref. The configuration is now passed the container in place of `divId`.

### CODE REVIEW

**Comment by mortendevold** [comment]
[Get rid of id on chart container in seatsio-vue](https://trello.com/c/fXnJtwzo/6848-get-rid-of-id-on-chart-container-in-seatsio-vue)

**Comment by mroloux** [comment]
👍 

Do we still need to set width and height of 100% on the container div, like we do in React? If not I assume the container div will not adapt to the dimensions of its parent.

**Comment by mortendevold** [comment]
> 👍
> 
> Do we still need to set width and height of 100% on the container div, like we do in React? If not I assume the container div will not adapt to the dimensions of its parent.

Hmm, will need to do something there apparently. I see the designer is very narrow currently. Checking

**Comment by mortendevold** [comment]
Seems to be fixed now 👍

**Review by mroloux — APPROVED** [review]

**Pull request merged**
