### PR TITLE
React to prop changes

### PR DESCRIPTION
**Pull request by mortendevold**
This PR makes `SeatsioSeatingChart` and `SeatsioEventManager` react to prop changes and rerender the chart. The Vue test page is also updated with a language dropdown to test the behaviour.

### CODE REVIEW

**Comment by mortendevold** [comment]
[[seatsio-vue]: Not able to change language](https://trello.com/c/Z5Jn2prp/6621-seatsio-vue-not-able-to-change-language)

**Review by mroloux — APPROVED** [review]
Works well 👏 

I assumed we could make this work for the designer as well, but there seems to be an issue with invoking `designer.rerender()`. Something to look into.

**Comment by mortendevold** [comment]
Fixed for designer as well after latest `seatsio-ui` release.

**Comment by mroloux** [comment]
> Fixed for designer as well after latest `seatsio-ui` release.

Nice 👍

**Pull request merged**
