### PR TITLE
Add TypeScript

### PR DESCRIPTION
**Pull request by mortendevold**
This PR adds TypeScript to seatsio-vue, with the intention of moving to release 3.0.0.

Changes:
- Adds TypeScript and seatsio-types dependency
- All types are re-exported from seatsio-vue, so they can be imported by library users without adding seatsio-types manually
- Moved to only ship ES module + types
- Cleaned up what goes into the NPM package, now only `dist` folder is included in addition to default package files.

Tested on new `vue create` project, where Intellisense and embeds work as expected.

### CODE REVIEW

**Comment by mortendevold** [comment]
[Add seatsio-types to vue client](https://trello.com/c/fFCYLuOA/5891-add-seatsio-types-to-vue-client)

**Comment by mroloux** [comment]
Looks good 👍 

I haven't been able to get code-completion on a test project to work though. But might be an IntellIJ issue.

Does that work for you? E.g. does your IDE show an error if you don't pass in a workspace key to the chart?

**Comment by mortendevold** [comment]
Yep, here's my test project in action:
ts-vue

Not sure why it suggests the props in the format they do, might be a Vue thing I'm not aware of. I'll give it a go with IntelliJ too.

**Comment by mroloux** [comment]
Ok cool. And are you able to import types (e.g. `Region`) from `seatsio-types`? That didn't work either for me (but again, must be my setup).

**Review by mroloux — APPROVED** [review]

**Comment by mroloux** [comment]
> Ok cool. And are you able to import types (e.g. `Region`) from `seatsio-types`? That didn't work either for me (but again, must be my setup).

Works fine when using a `link:../seatsio-vue` instead of `yarn link`

**Pull request merged**
